# Generated by Django 4.1.3 on 2022-11-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportlockerShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropa',
            name='imagen',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='zapatilla',
            name='imagen',
            field=models.TextField(default=''),
        ),
    ]
