# Generated by Django 4.1.3 on 2022-11-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportlockerShop', '0003_remove_ropa_talla_remove_zapatilla_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropa',
            name='articuloTop',
            field=models.BooleanField(default=False),
        ),
    ]
