# Generated by Django 4.1.3 on 2022-11-23 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportlockerShop', '0005_alter_ropa_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='contrasenya',
        ),
    ]
